apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandora-actions-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pandora-actions
  template:
    metadata:
      labels:
        app: pandora-actions
    spec:
      containers:
        - name: pandora-actions
          image: isaacaderogba/pandora-actions
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 250m
              memory: 384Mi
            limits:
              cpu: 625m
              memory: 768Mi
          readinessProbe:
            httpGet:
                port: 8000
                path: /health/probe
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 15
            timeoutSeconds: 15
          livenessProbe:
            httpGet:
                port: 8000
                path: /health/probe
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: pandora-actions-srv
spec:
  type: ClusterIP
  selector:
    app: pandora-actions
  ports:
    - name: pandora-actions
      protocol: TCP
      port: 8000
      targetPort: 8000
