name: agent-test

on:
  pull_request:
    paths:
      - "services/agent/**"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd services/agent && npm i && npm run build
